### ISSUE TITLE
This vs realm

### ISSUE THREAD

**Issue by ethantran** [bjornd/react-native-cbl#2]
Hi, the company I work for is looking to use either couchbase or realm. It looks like realm has better react native support. All couchbase react native integrations seem to be inactive, still on 1.x, or not officially supported by couchbase. What do you think about using couchbase and react native? Are there any cons we should be aware of?

**Comment by bjornd** [comment]
Unfortunately Couchbase never aimed to officially support React Native. So, yes current implementations are rather limited and they do not support Couchbase Lite 2. Last couple of months I've been working to add support for Couchbase Lite 2 under the branch [feature/cbl2](https://github.com/bjornd/react-native-cbl/compare/feature/cbl2). The only big feature missing is queries but it also should be ready in a couple of weeks. 

In general I don't see any big issues accessing Couchbase Lite from React Native.

**Comment by imaadhrizni** [comment]
@bjornd it's sad that Couchbase never supported it officially. Even I was at crossroads of choosing different options. Its really nice to see the work you've done. I checked out your `feature/cbl2` branch. Thanks for the support you've provided thus far. Can't wait for the rest of the stuff to be completed. Best regards 👍 💯
